#version 450 core

#extension GL_ARB_compute_shader : enable
#extension GL_ARB_shader_storage_buffer_object : enable

layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

/* Structures */

struct Vertex {
  float x, y, z;
  float tessLevel;
};

/* Variables */

layout(std430, binding = 0) buffer VertexBuffer { 
  vec4 u_VertexBuffer[];
};

/* Functions */

void main() {
  uint gid = gl_GlobalInvocationID.x;

  u_VertexBuffer[gid][3] = 4;
}